[package]
name = "godot-gif-getter"
version = "0.1.0"
authors = ["Tim Yuen <theaznyune@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
gdnative = "0.9.3"
gif = "0.11.1"
